# Docker Compose configuration for Loki Monitoring Stack
services:
  # Loki - Log aggregation system
  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"  # Expose Loki API port
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki-data:/loki  # Persistent storage for logs
    restart: unless-stopped  # Automatically restart container

  # Promtail - Log collector that sends logs to Loki
  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - /var/log:/var/log:ro  # Mount host logs as read-only
      - ./promtail-config.yml:/etc/promtail/promtail.yaml  # Custom configuration
    command: -config.file=/etc/promtail/promtail.yaml
    restart: unless-stopped  # Automatically restart container

  # Grafana - Visualization platform
  grafana:
    image: grafana/grafana:10.2.3
    ports:
      - "3000:3000"  # Expose Grafana web interface
    volumes:
      - grafana-storage:/var/lib/grafana  # Persistent storage for dashboards and settings
    restart: unless-stopped  # Automatically restart container
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Default admin password
      - GF_SECURITY_ADMIN_USER=admin      # Default admin username

# Persistent volumes for data storage
volumes:
  loki-data:       # Stores log data
  grafana-storage: # Stores Grafana dashboards and settings
